services:
  ollama-redis:
    container_name: ollama-redis
    image: redis/redis-stack
    env_file:
      - redis/redis-env.env
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  ollama-jarvis:
    container_name: ollama-jarvis
    build: ./ollama
    ports:
      - "11434:11434"
    environment:
      - gpus=all
      - OLLAMA_MODELS=/app/volumes
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - /home/dustin/git/MapleJarvis:/app
      - ./.ollama:/root/.ollama
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    healthcheck:
      test: ["CMD-SHELL", "curl -f ollama-jarvis:11434 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    